### ISSUE TITLE
Zarr assets are empty when opened as xarray.Dataset

### ISSUE THREAD

**Issue by captaincoordinates** [EOPF-Sample-Service/eopf-stac#26]
Many STAC items with Zarr assets appear to follow a common structure:
- a `product` asset references a Zarr group hierarchy and provides a `xarray:open_datatree_kwargs` property indicating that the asset should be accessed as a DataTree within xarray
- one or more additional assets reference a flat (non-nesting) Zarr group and provide a `xarray:open_dataset_kwargs` property indicating that the asset should be accessed as a Dataset within xarray.

This relationship is implied through asset hrefs, for example in the following two (partial) assets exist in [this](https://stac.core.eopf.eodc.eu/collections/sentinel-2-l2a/items/S2B_MSIL2A_20250522T125039_N0511_R095_T26TML_20250522T133252) STAC item `SR_10m`'s href is `product`'s href plus a path suffix:
```JSON
"product": {
  "href": "https://.../S2B_MSIL2A_20250522T125039_N0511_R095_T26TML_20250522T133252.zarr",
  ...
  "xarray:open_datatree_kwargs": {
    "chunks": {},
    "engine": "eopf-zarr",
    "op_mode": "native"
  }
}
...
"SR_10m": {
  "href": "https://.../S2B_MSIL2A_20250522T125039_N0511_R095_T26TML_20250522T133252.zarr/measurements/reflectance/r10m",
  ...
  "xarray:open_dataset_kwargs": {
    "chunks": {},
    "engine": "eopf-zarr",
    "op_mode": "native"
  }
}
```

The `product` DataTree can be used to access non-empty data in the `/measurements/reflectance/r10m` group that is also represented by the `SR_10m` asset. However, accessing the `SR_10m` asset directly as a Dataset returns an empty data structure. I believe this suggests a problem with the structure of the Zarr store?

```python
import fsspec
import xarray as xr
from pystac_client import Client

client = Client.open("https://stac.core.eopf.eodc.eu/")
collection = client.get_collection(collection_id="sentinel-2-l2a")
item = collection.get_item(
    id="S2B_MSIL2A_20250522T125039_N0511_R095_T26TML_20250522T133252"
)
dt_asset = item.assets["product"]
ds_sr10m_asset = item.assets["SR_10m"]

dt = xr.open_datatree(
    fsspec.get_mapper(dt_asset.href),
    **dt_asset.extra_fields["xarray:open_datatree_kwargs"],
)
ds_sr10m = xr.open_dataset(fsspec.get_mapper(ds_sr10m_asset.href), **ds_sr10m_asset.extra_fields["xarray:open_dataset_kwargs"])

print(dt["/measurements/reflectance/r10m"].to_dataset().nbytes) # 3858108480
print(len(dt["/measurements/reflectance/r10m"].to_dataset().dims)) # 2
print(ds_sr10m.nbytes)  # 0
print(len(ds_sr10m.dims))  # 0
```

**Comment by konstntokas** [comment]
Fixed by https://github.com/EOPF-Sample-Service/xarray-eopf/pull/53. 

We will release a new version next week. I will share it here once we have the new version available via pip and conda/mamba

**Comment by konstntokas** [comment]
> [@captaincoordinates](https://github.com/captaincoordinates) The lastest release xarray-eopf v0.1.1 should fix this bug:
> 
> https://anaconda.org/conda-forge/xarray-eopf https://pypi.org/project/xarray-eopf/

@captaincoordinates I added a small example at the bottom of this [example notebook](https://github.com/EOPF-Sample-Service/xarray-eopf/blob/main/examples/open-sen2.ipynb): last section *Accessing subgroups via S3 path*

**Comment by captaincoordinates** [comment]
@konstntokas thanks for your input on this, however I still see the same issue with v0.1.1.

[This repo](https://github.com/captaincoordinates/eopf-stac-issue-26) provides a containerised reproducible example.

**Comment by captaincoordinates** [comment]
@konstntokas running from the main branch addresses the problem and I now see the following output, which verifies accessing the group directly and via the datatree behaves the same.

```sh
testing...
fetching item
opening datatree
opening dataset
gathering stats
-----
from datatree, nbytes: 3858108480
from datatree, dims: 2
from dataset, nbytes: 3858108480
from dataset, dims: 2

dependencies:
xarray==2025.6.1
-e git+https://github.com/EOPF-Sample-Service/xarray-eopf.git@58fee611a725e2b11336c79b2583dc5e3761f9d7#egg=xarray_eopf
```

**Comment by konstntokas** [comment]
Great so I will do a release. I will let you know once it is available via conda-forge.

**Comment by emmanuelmathot** [comment]
reported in https://gitlab.eopf.copernicus.eu/cpm/eopf-cpm/-/issues/773

**Comment by emmanuelmathot** [comment]
proposed solution in CPM: https://gitlab.eopf.copernicus.eu/cpm/eopf-cpm/-/merge_requests/908
